apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kc0xwww2s-dotnet-basic 
  description: Secure Supply Chain Example for C# .Net 6.0 example with advanced continuous integration pipeline covering building, CVE scanning, security scanning, signatures,  attestations, SLSA provenance and SBOM along with Gitops-based continuous deployment   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=kc0xwww2s-dotnet-basic
    backstage.io/kubernetes-id: kc0xwww2s-dotnet-basic 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: xjiangorg/kc0xwww2s-dotnet-basic
    nexus-repository-manager/docker.image-name: rhtap/rhtap-qe-dotnet-basic
  tags: ["net", "sscs", "sbom", "acs"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 